### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by ionelmc** [wyplay/pytracemalloc#4]
I've created this ppa: https://launchpad.net/~ionel-mc/+archive/pytracemalloc with track_free_list.patch builds of python

The 3.4 patch doesn't apply cleanly on python3.2 and python3.3 but if you fix it I can add the python3.x builds in the ppa too.

**Comment by cmuller** [comment]
I am freezing this project. Please report your issue in the official repo https://github.com/haypo/pytracemalloc.
